model_name_or_path: t5-small
output_dir: runs/t5-small-cnn
max_source_length: 512
max_target_length: 128
min_target_length: 32
num_train_epochs: 3
learning_rate: 0.0003
weight_decay: 0.01
warmup_ratio: 0.03
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_accumulation_steps: 2
logging_steps: 50
eval_strategy: steps
eval_steps: 500
save_steps: 1000
fp16: true
seed: 42
